### PR TITLE
fixed wrong example in 40

### PR DESCRIPTION
**Pull request by tonsky**

### CODE REVIEW

**Comment by zaitsev85** [comment]
I don't think you're right. It's a stateless draw, it discards the state. Hence `nil`.

**Comment by tonsky** [comment]
well, my test say different

```
(test/deftest test-interact
  (binding [*ctx* {"statelessdraw" (parse "ap ap c ap ap b b ap ap b ap b ap cons 0 ap ap c ap ap b b cons ap ap c cons nil ap ap c ap ap b cons ap ap c cons nil nil")
                   ":67108929"     (parse "ap ap b ap b ap ap s ap ap b ap b ap cons 0 ap ap c ap ap b b cons ap ap c cons nil ap ap c cons nil ap c cons")}]
    (test/are [a e] (= e (run a))
      "ap ap statelessdraw x0 x1"                         (make-list 0 "x0" (make-list (make-list "x1")))
      "ap ap ap interact statelessdraw nil ap ap vec 1 0" (make-cons "nil" (make-list (make-list (picture [1 0]))))
      "ap ap ap interact statelessdraw nil ap ap vec 2 3" (make-cons "nil" (make-list (make-list (picture [2 3]))))
      "ap ap ap interact statelessdraw nil ap ap vec 4 1" (make-cons "nil" (make-list (make-list (picture [4 1]))))
```

**Comment by zaitsev85** [comment]
I'LL HAVE TO CHECK OUR RAW TELESCOPE DATA THEN

**Comment by zaitsev85** [comment]
Whoopsie daisy! Fixed the original picture that was corrupted due to cosmic rays probably. Nice catch!

**Pull request closed without merging**
