### PR TITLE
Message 10: interpret and update Haskell annotation code

### PR DESCRIPTION
**Pull request by mx00s**

### CODE REVIEW

**Comment by zaitsev85** [comment]
Should we really create a copy of the whole `annotate.hs` file when a single line changes? I usually replace the existing file and rely on Git to keep track of changes.

**Comment by mx00s** [comment]
I could go either way on this. Given the way the documentation is creating a narrative of our discoveries along the way I have a slight preference to avoid leaking interpretations about subsequent messages in earlier writeups.

**Comment by zaitsev85** [comment]
You have a valid point, but:

1. If we go this way, we should update all the previous messages with diffs to be consistent. Sounds like a lot of work. Not sure if you're inclined to do this :-)
2. It bloats the downloadable PDF version a lot, and I'd like to have a nice PDF version for my... PhD thesis, you know.

**Comment by mx00s** [comment]
That's also a good point. I'll push a commit soon that makes the change in `annotate.hs` instead.

**Pull request merged**
